{{- if .Values.observability.alertmanager.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dineos.fullname" . }}-alertmanager
  labels:
    {{- include "dineos.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9093
      targetPort: http
      protocol: TCP
  selector:
    {{- include "dineos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
{{- end }}
