apiVersion: v1
kind: Service
metadata:
  name: {{ include "dineos.fullname" . }}-api
  labels:
    {{- include "dineos.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "dineos.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
