{{- if .Values.dependencies.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-realm
  labels:
    {{- include "dineos.labels" . | nindent 4 }}
type: Opaque
data:
  realm-export.json: {{ tpl (.Files.Get "files/realm-export.json") . | b64enc }}
{{- end }}
